CREATE TABLE hr.performance_reviews (
    review_id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id      NUMBER REFERENCES hr.employees(employee_id),
    review_period    DATE,
    performance_grade CHAR(1) 
    comments         VARCHAR2(200)
);

--Sample data to insert into table for testing purposes:

INSERT INTO hr.performance_reviews (employee_id, review_period, performance_grade, comments)
VALUES (101, TO_DATE('2026-02-01','YYYY-MM-DD'), 'A', 'Outstanding leadership');

INSERT INTO hr.performance_reviews (employee_id, review_period, performance_grade, comments)
VALUES (102, TO_DATE('2026-02-01','YYYY-MM-DD'), 'B', 'Strong performance overall');

INSERT INTO hr.performance_reviews (employee_id, review_period, performance_grade, comments)
VALUES (103, TO_DATE('2026-02-01','YYYY-MM-DD'), 'D', 'Needs improvement');

COMMIT;
